/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class WetterGUI extends javax.swing.JFrame {

    /**
     * Creates new form WetterGUI
     */
    private WetterTableModel wtm = new WetterTableModel();
    public WetterGUI() {
        initComponents();
        tableWeatherStations.setModel(wtm);
        tableWeatherStations.setDefaultRenderer(Object.class, new WetterTableRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableWeatherStations = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        menuStations = new javax.swing.JMenu();
        miAddStation = new javax.swing.JMenuItem();
        miRemoveStation = new javax.swing.JMenuItem();
        menuValues = new javax.swing.JMenu();
        miSetTemperature = new javax.swing.JMenuItem();
        miSetHumidity = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableWeatherStations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableWeatherStations);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        menuStations.setText("Stations");

        miAddStation.setText("Add Weather Station");
        miAddStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddStationActionPerformed(evt);
            }
        });
        menuStations.add(miAddStation);

        miRemoveStation.setText("Remove Weather Station");
        miRemoveStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemoveStationActionPerformed(evt);
            }
        });
        menuStations.add(miRemoveStation);

        menuBar.add(menuStations);

        menuValues.setText("Values");

        miSetTemperature.setText("Set Temperature");
        menuValues.add(miSetTemperature);

        miSetHumidity.setText("Set Humidity");
        menuValues.add(miSetHumidity);

        menuBar.add(menuValues);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAddStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddStationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAddStationActionPerformed

    private void miRemoveStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemoveStationActionPerformed
        wtm.removeStation(tableWeatherStations.getSelectedRows());
    }//GEN-LAST:event_miRemoveStationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WetterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WetterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WetterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WetterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WetterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuStations;
    private javax.swing.JMenu menuValues;
    private javax.swing.JMenuItem miAddStation;
    private javax.swing.JMenuItem miRemoveStation;
    private javax.swing.JMenuItem miSetHumidity;
    private javax.swing.JMenuItem miSetTemperature;
    private javax.swing.JTable tableWeatherStations;
    // End of variables declaration//GEN-END:variables
}
